SUBROUTINE EQUILIBRE(K,gamm,PSAT)

USE MODULE_DIMENSION
USE MODULE_OPERATOIRE


  IMPLICIT NONE

  INTEGER :: i
  DOUBLE PRECISION,DIMENSION(NC) :: gamm
  DOUBLE PRECISION,DIMENSION(NC) :: PSAT
  DOUBLE PRECISION,DIMENSION(NC) :: K

  do i=1,NC
    K(i)=gamm(i)*PSAT(i)/PRESSION
  enddo


endsubroutine
