subroutine mHV(Y,HVAP,TEMP)
  USE MODULE_DIMENSION
  USE MODULE_INITIALISATION
  USE MODULE_OPERATOIRE
  USE MODULE_THERMODYNAMIC
  implicit NONE

  DOUBLE PRECISION,DIMENSION(1:NC) :: Y
  DOUBLE PRECISION :: HVAP,TEMP
  INTEGER :: i

  HVAP=0 !REFERENCE GAZ À T= 298.15 K
  do i=1,NC
    HVAP= HVAP + Y(i)*CPvap(i)*(TEMP-TREF)
  enddo
endsubroutine
