SUBROUTINE CALCUL_TROSEE(Y,TB,X)
  USE MODULE_DIMENSION
  USE MODULE_INITIALISATION
  USE MODULE_OPERATOIRE
  USE MODULE_THERMODYNAMIC
  IMPLICIT none

  INTEGER :: I,J
  DOUBLE PRECISION, DIMENSION(1:NC) :: Y,X
  DOUBLE PRECISION,DIMENSION(NC) :: gamm,gammdt,k,kdt
  DOUBLE PRECISION :: TBDT,TB,DT,A,B
  DOUBLE PRECISION,DIMENSION(NC) :: PSAT,PSATDT

  DT = 0.00001
  TBDT = TB + DT
  A = 0

  CALL NRTL(gamm,Y,TB)
  CALL CALCULPSAT(TB,PSAT)
  CALL EQUILIBRE(K,gamm,PSAT)
  DO i=1,NC
    A = A + Y(I)/K(i)
  ENDDO


  DO WHILE(DABS(A-1)>=1D-10) !METHODE DE NEWTON RAPHSON + PERTURBATION NUMÉRIQUE
    CALL NRTL(gammDT,Y/K,TBDT)
    CALL NRTL(gamm,Y/K,TB)


    CALL CALCULPSAT(TBDT,PSATDT)
    CALL CALCULPSAT(TB,PSAT)

    CALL EQUILIBRE(KDT,gammDT,PSATDT)
    CALL EQUILIBRE(K,gamm,PSAT)

    A = 0
    B = 0
        DO i=1,NC
          A = A + Y(I)/K(i)
          B = B + Y(I)*((1/KDT(i))-(1/K(i)))
        ENDDO
    TB = TB - DT*(A-1)/(B)
    TBDT = TB + DT
  enddo
  X=Y/K

END SUBROUTINE
