SUBROUTINE CALCUL_TBULLE(X,TB)
  USE MODULE_DIMENSION
  USE MODULE_INITIALISATION
  USE MODULE_OPERATOIRE
  USE MODULE_THERMODYNAMIC
  IMPLICIT none

  INTEGER :: I,J
  DOUBLE PRECISION, DIMENSION(1:NC) :: X
  DOUBLE PRECISION,DIMENSION(NC) :: gamm,gammdt,k,kdt
  DOUBLE PRECISION :: TBDT,TB,DT,A,B
  DOUBLE PRECISION,DIMENSION(NC) :: PSAT,PSATDT


  TB=320. !INITIALIATION ABSTRAITE
  DT = 0.0001
  TBDT = TB + DT
  A = 0

  CALL NRTL(gamm,X,TB)
  CALL CALCULPSAT(TB,PSAT)
  CALL EQUILIBRE(K,gamm,PSAT)
  DO i=1,NC
    A = A + X(I)*K(i)
  ENDDO




  DO WHILE(DABS(A-1)>=1D-6) !METHODE DE NEWTON RAPHSON + PERTURBATION NUMÉRIQUE

    CALL NRTL(gammDT,X,TBDT)
    CALL NRTL(gamm,X,TB)


    CALL CALCULPSAT(TBDT,PSATDT)
    CALL CALCULPSAT(TB,PSAT)

    CALL EQUILIBRE(KDT,gammDT,PSATDT)
    CALL EQUILIBRE(K,gamm,PSAT)

    A = 0
    B = 0
        DO i=1,NC
          A = A + X(I)*K(i)
          B = B + X(I)*(KDT(i)-K(i))
        ENDDO
    TB = TB - DT*(A-1)/(B)
    TBDT = TB + DT

  enddo

END SUBROUTINE
