SUBROUTINE NORME_VECTEUR(A,TAILLE,NORME)
  USE MODULE_DIMENSION
  USE MODULE_OPERATOIRE
  USE MODULE_INITIALISATION
  IMPLICIT NONE

  INTEGER :: I,J,TAILLE
  DOUBLE PRECISION :: NORME,A2
  DOUBLE PRECISION, DIMENSION(1:TAILLE) :: A

  NORME=0.
  A2=0
  DO I=1,TAILLE
    A2=A2+A(I)*A(I)
  ENDDO

  NORME = DSQRT(A2)/TAILLE
  PRINT*,'NORME RESIDU EN COURS :',NORME


ENDSUBROUTINE
