SUBROUTINE CALCULPSAT(TEMP,PSAT)
  USE MODULE_DIMENSION
  USE MODULE_INITIALISATION
  USE MODULE_OPERATOIRE
  USE MODULE_THERMODYNAMIC
  IMPLICIT NONE

  INTEGER :: i, j
  DOUBLE PRECISION,DIMENSION(NC) :: PSAT
  DOUBLE PRECISION ::  TEMP

  PSAT=0.

    do j = 1,NC
      PSAT(j) = exp( COEFPSAT(1,j)+(COEFPSAT(2,j)/TEMP)+(COEFPSAT(3,j)*log(TEMP))+(COEFPSAT(4,j)*TEMP**(COEFPSAT(5,j))))
    end do

endsubroutine
