SUBROUTINE JACOBIEN_MRSL01(X,FX,JACOB,TAILLE)
  USE MODULE_DIMENSION
  USE MODULE_INITIALISATION
  USE MODULE_OPERATOIRE
  USE MODULE_THERMODYNAMIC
  IMPLICIT NONE
  INTEGER :: I,J,K,TAILLE
  DOUBLE PRECISION :: DX
  DOUBLE PRECISION, DIMENSION(1:TAILLE) :: X,FX
  DOUBLE PRECISION, DIMENSION(1:TAILLE,1:TAILLE) :: JACOB
  DOUBLE PRECISION, DIMENSION(:),ALLOCATABLE :: XX,FXX



  ALLOCATE(XX(1:TAILLE),FXX(1:TAILLE))
  JACOB=0
  XX=0
  DX=1.D-3
  FXX=0



  CALL RESIDU(X,FX)
  XX=X

  DO I=1,TAILLE
      XX(I)=X(I)*(1.+DX)
      CALL RESIDU(XX,FXX)
      DO j=1,TAILLE
          IF (X(I)==0) THEN
              JACOB(J,I)=(FXX(J)-FX(J))/(DX)
          ELSE
              JACOB(J,I)=(FXX(J)-FX(J))/(DX*X(I))
          ENDIF
      ENDDO
      XX(I)=X(I)
  ENDDO



  DEALLOCATE(XX,FXX)

ENDSUBROUTINE
