MODULE MODULE_INITIALISATION
    IMPLICIT NONE
    DOUBLE PRECISION :: TBULLE, TROSEE
    DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: XPIED, YPIED, XTETE, YTETE
    DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: DV, DL, F, Q_COL
    DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: Z
    INTEGER :: IDV,ICV,IT,ICL,IDL,IBMT,IBMP,IBE,IEQ,IST
ENDMODULE
