MODULE MODULE_THERMODYNAMIC
    IMPLICIT NONE
    DOUBLE PRECISION :: PRESSION, TREF
    DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: TEB
    DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: HVAPO
    DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: CPVAP
    DOUBLE PRECISION, DIMENSION(:), ALLOCATABLE :: CPLIQ
    DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: COEFPSAT
    DOUBLE PRECISION, DIMENSION(:,:), ALLOCATABLE :: ALPHA,C

ENDMODULE
