MODULE MODULE_DIMENSION
    IMPLICIT NONE
    INTEGER :: N   !NOMBRE D'ÉTAGE THÉORIQUE
    INTEGER :: NC   !NOMBRE DE CONSTITUANTS
    INTEGER :: NB_ALIM !NOMBRE D'ALIMENTATION
    INTEGER :: NB_DL, NB_DV ! NOMBRE DE SOUTIRAGE LIQUIDE ET VAPEUR
    INTEGER, DIMENSION(:), ALLOCATABLE::ETAGE_ALIM
    INTEGER, DIMENSION(:), ALLOCATABLE::ETAGE_DL
    INTEGER, DIMENSION(:), ALLOCATABLE::ETAGE_DV
ENDMODULE
